### ISSUE TITLE
Задача: мультибраузерное тестирование

### ISSUE THREAD

**Issue by Itsnoby** [NickyBoch/Twitter#15]
Необходимо добавить возможность запускать тесты на браузере Chrome или Firefox на выбор. 
Запуск теста необходимо реализовать таким образом, чтобы выбор браузера выполнялся через передачу параметра запуска, например:
```sh
ant testAll -Dbrowser=firefox
```

**Comment by NickyBoch** [comment]
добавил возможность запускать тесты на браузере Chrome или Firefox на выбор
