### ISSUE TITLE
В скрипте нужно предусматривать завершение при любой ситуации

### ISSUE THREAD

**Issue by Itsnoby** [NickyBoch/Twitter#18]
Окей, мы дожидаемся пока количество твитов не увеличится. А что если система дала сбой, и значение у нас не обновится никогда? Когда в таком случае будет выход из метода?
Для подобного рода ожиданий нужно всегда учитывать тайм-аут. Допустим, если значение не обновилось в течении одной минуты, выдать ошибку.
![2015-06-16_15-17-08](https://cloud.githubusercontent.com/assets/1472494/8182743/01d601fa-143b-11e5-99a3-e5315e12f796.png)

**Comment by NickyBoch** [comment]
добавил секундомер для выхода через 60 секунд
