### ISSUE TITLE
Задача: вынести работу с входными данными в отдельный класс (статик провайдер)

### ISSUE THREAD

**Issue by Itsnoby** [NickyBoch/Twitter#19]
Подобного рода действия с данными желательно выносить в отдельные классы, и потом использовать во всех тестах
![2015-06-16_15-23-08](https://cloud.githubusercontent.com/assets/1472494/8182795/b69edba2-143b-11e5-9429-dfb0d08e464f.png)

**Comment by NickyBoch** [comment]
сделал
