### ISSUE TITLE
Задача: разработка теста на ретвит

### ISSUE THREAD

**Issue by Itsnoby** [NickyBoch/Twitter#20]
Пользователь подписан на других пользователей.

Шаги:
1. Открыть одного из читаемых пользователей
2. Сделать ретвит записи, которая была сделана 1 день назад
3. Проверить, что ретвит был обудликован в профиле. 
Проверить, что количество твитов обновилось корректно.
Проверить, что дата публикации записи, которая была ретвитнута, не изменилась.
Проверить на странице читаемого пользователся, что дата публикации записи, которая была ретвитнута, не изменилась.
Проверить, что количество ретвитов записи изменилось корректно

**Comment by NickyBoch** [comment]
Done
