### ISSUE TITLE
Задача: разработка теста на ретвит 2

### ISSUE THREAD

**Issue by Itsnoby** [NickyBoch/Twitter#21]
В профиле имеется ретвит записи.

Шаги:
1. Открыть профиль, убрать ретвит записи.
3. Проверить, что ретвит был удален с ленты пользователя. 
Проверить, что количество твитов обновилось корректно.
Проверить, что запись отображается на странице читаемого пользователя
Проверить на странице читаемого пользователся, что дата публикации записи не изменилась.
Проверить, что количество ретвитов записи изменилось корректно

**Comment by NickyBoch** [comment]
Done
