### ISSUE TITLE
Нужно выполнять те же действия, которые выполняет пользователь. Нельзя упрощать логику хаками.

### ISSUE THREAD

**Issue by Itsnoby** [NickyBoch/Twitter#4]
![2015-06-12_18-28-56](https://cloud.githubusercontent.com/assets/1472494/8133417/ed28ee5a-1130-11e5-9286-620153a5c3d4.png)
![2015-06-12_18-29-28](https://cloud.githubusercontent.com/assets/1472494/8133433/fea84ec8-1130-11e5-867a-4d727b41c2b4.png)

**Comment by NickyBoch** [comment]
добавил смену атрибута с помощью javascripta. теперь меню открывается и происходит нажатие на кнопку.
