### ISSUE TITLE
Такой страницы нет. Элементы относятся к разным блокам.

### ISSUE THREAD

**Issue by Itsnoby** [NickyBoch/Twitter#5]
![2015-06-12_18-31-19](https://cloud.githubusercontent.com/assets/1472494/8133521/7ddcd452-1131-11e5-926b-a70839d63dd0.png)

**Comment by NickyBoch** [comment]
создал страницу MainPage добавил нажатие элементов управления на ней
переименовал страницу SendMessagePage в страницу SendMessageDialogPage
