### ISSUE TITLE
Локаторы необходимо описывать точно, чтобы находить конкретный элемент

### ISSUE THREAD

**Issue by Itsnoby** [NickyBoch/Twitter#6]
![2015-06-12_18-35-47](https://cloud.githubusercontent.com/assets/1472494/8133597/007d0e7c-1132-11e5-80d8-c03d04cbd88d.png)
![2015-06-12_18-37-05](https://cloud.githubusercontent.com/assets/1472494/8133603/0b8e9efc-1132-11e5-99fa-30c9886a20b9.png)

**Comment by NickyBoch** [comment]
прописал локатор через id и перенес в MainPage
